### ISSUE TITLE
as using kaist urban17 , how to modify the test_config.yaml?

### ISSUE THREAD

**Issue by ViryaGit** [hyye/lio-mapping#24]
as you have tested on urban17, can you provide the config file for us?

**Comment by hyye** [comment]
You may take the following one as an example. In our tests, we skipped first several seconds to ensure enough IMU excitations.
```yaml
%YAML:1.0

min_plane_dis: 0.2

min_match_sq_dis: 1.0

corner_filter_size: 0.2
surf_filter_size: 0.4
map_filter_size: 0.6

window_size: 7
opt_window_size: 5

init_window_factor: 1

# Extrinsic parameter between IMU and Camera.
estimate_extrinsic: 1   # 0  Have an accurate extrinsic parameters. We will trust the following imu^R_cam, imu^T_cam, don't change it.
                        # 1  Have an initial guess about extrinsic parameters. We will optimize around your initial guess.
                        # 2  Don't know anything about extrinsic parameters. You don't need to give R,T. We will try to calibrate it. Do some rotation movement at beginning.
opt_extrinsic: 1

extrinsic_rotation: !!opencv-matrix
  rows: 3
  cols: 3
  dt: d
  # urban17 right
  data: [ -4.91913910e-01,  -5.01145813e-01,  -7.11950546e-01,
           7.13989130e-01,  -7.00156621e-01,  -4.78439170e-04,
          -4.98237120e-01,  -5.08560301e-01,   7.02229444e-01]

#Translation from imu frame to laser frame, laser^T_imu
extrinsic_translation: !!opencv-matrix
  rows: 3
  cols: 1
  dt: d
  # urban17 right
  data: [-0.102845, -0.40955, -0.499168]

run_optimization: 1

update_laser_imu: 1
gravity_fix: 1

plane_projection_factor: 0

imu_factor: 1
point_distance_factor: 1

prior_factor: 0

marginalization_factor: 1

odom_io: 3

pcl_viewer: 0

acc_n: 0.15
gyr_n: 0.015
acc_w: 0.0003
gyr_w: 3.0e-5
g_norm: 9.805

enable_deskew: 1
cutoff_deskew: 0

keep_features: 0

msg_time_delay: 0.05
```
